### PR TITLE
Reconnect fix for knx node

### LINKED ISSUE #242: knx node does not reconnect on network failure
```
Oct 28 19:51:29 bulan stampzilla-knx[10907]: WARN[3317690] Disconnected from KNX gateway
Oct 28 19:51:29 bulan stampzilla-knx[10907]: WARN[3317690] Disconnect from KNX gateway done
Oct 28 19:51:29 bulan stampzilla-knx[10907]: WARN[3317690] Going to try again in 10s
Oct 29 00:00:00 bulan stampzilla-knx[10907]: ERRO[3332600]
Oct 29 07:04:56 bulan stampzilla-knx[10907]: ERRO[3358096]
Oct 29 16:22:59 bulan stampzilla-knx[10907]: ERRO[3391579]
Oct 29 16:22:59 bulan stampzilla-knx[10907]: ERRO[3391579]
restarted it with systemctl...
Oct 29 20:05:59 bulan systemd[1]: Stopping stampzilla-knx...
Oct 29 20:05:59 bulan stampzilla-knx[10907]: INFO[3404959] Stopping node reader because:context canceled
Oct 29 20:05:59 bulan stampzilla-knx[10907]: INFO[3404959] websocket: stopping reconnect because err: context canceled
Oct 29 20:05:59 bulan stampzilla-knx[10907]: ERRO[3404959] websocket: Stopping writePump because err: context canceled
Oct 29 20:05:59 bulan stampzilla-knx[10907]: ERRO[3404959] websocket: readPump error:websocket: close 1000 (normal)
Oct 29 20:05:59 bulan systemd[1]: Stopped stampzilla-knx.

```

### PR DESCRIPTION
**Pull request by jonaz**
Also fixed graceful shutdown and all race conditions detected by go run
-race *.go

Some changes are automaticly formatted by my editor (vim). 

Fixes #242

### CODE REVIEW

File: nodes/stampzilla-knx/tunnel.go [hunk 1]
```diff
@@ -15,21 +16,26 @@ import (
 )
 
 type tunnel struct {
-	Node      *node.Node
```
Comment (jonaz) [inline nodes/stampzilla-knx/tunnel.go:18]: Also aligned this struct for memory effiency (vim lints about that for me now days... ) 
https://medium.com/@felipedutratine/how-to-organize-the-go-struct-in-order-to-save-memory-c78afcf59ec2

**Review by stamp — APPROVED** [review]
